name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '12.0'

    - name: Accept Android SDK Licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean --info

    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug --info --stacktrace --scan
        ./gradlew testDebugUnitTest --info --stacktrace
        ./gradlew lintDebug --info --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error 