name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Check project structure
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Checking accounting_app directory:"
        ls -la accounting_app || echo "accounting_app directory not found"
        echo "Creating accounting_app directory if it doesn't exist"
        mkdir -p accounting_app

    - name: Initialize Gradle project
      working-directory: accounting_app
      run: |
        if [ ! -f "gradlew" ]; then
          echo "Initializing Gradle project..."
          gradle wrapper
        fi

    - name: Grant execute permission for gradlew
      working-directory: accounting_app
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: accounting_app
      run: ./gradlew build

    - name: Build Debug APK
      working-directory: accounting_app
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: accounting_app/app/build/outputs/apk/debug/app-debug.apk

    - name: Build Release APK
      working-directory: accounting_app
      run: ./gradlew assembleRelease

    - name: Sign Release APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: accounting_app/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: accounting_app/app/build/outputs/apk/release/app-release-signed.apk 