name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'اختر العملية المطلوبة'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - download

jobs:
  build:
    if: github.event.inputs.action == 'build' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create keystore file
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks
      - name: Create gradle.properties
        run: |
          echo "RELEASE_STORE_FILE=keystore.jks" >> app/gradle.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> app/gradle.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> app/gradle.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> app/gradle.properties
      - name: Create proguard-rules.pro
        run: |
          cat > app/proguard-rules.pro << 'EOL'
          # Retrofit
          -keepattributes Signature
          -keepattributes *Annotation*
          -keep class retrofit2.** { *; }
          -keepclasseswithmembers class * {
              @retrofit2.http.* <methods>;
          }
          -keepclassmembers,allowshrinking,allowobfuscation interface * {
              @retrofit2.http.* <methods>;
          }

          # OkHttp
          -keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
          -dontwarn org.codehaus.mojo.animal_sniffer.*
          -dontwarn okhttp3.internal.platform.ConscryptPlatform
          -dontwarn org.conscrypt.ConscryptHostnameVerifier

          # Gson
          -keepattributes Signature
          -keepattributes *Annotation*
          -dontwarn sun.misc.**
          -keep class com.google.gson.** { *; }
          -keep class * implements com.google.gson.TypeAdapterFactory
          -keep class * implements com.google.gson.JsonSerializer
          -keep class * implements com.google.gson.JsonDeserializer

          # Keep your model classes
          -keep class com.hillal.hhhhhhh.data.model.** { *; }
          -keep class com.hillal.hhhhhhh.data.remote.** { *; }

          # Keep Room
          -keep class * extends androidx.room.RoomDatabase
          -keep @androidx.room.Entity class *
          -keep @androidx.room.Dao interface *

          # Keep Navigation Component
          -keepnames class androidx.navigation.fragment.NavHostFragment
          -keepnames class * extends android.os.Parcelable
          -keepnames class * extends java.io.Serializable

          # Keep ViewBinding
          -keep class * implements androidx.viewbinding.ViewBinding {
              public static *** bind(android.view.View);
              public static *** inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean);
          }

          # Keep Kotlin Coroutines
          -keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
          -keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

          # Keep Lifecycle
          -keep class * extends androidx.lifecycle.ViewModel
          -keep class * extends androidx.lifecycle.AndroidViewModel
          -keep class * extends androidx.lifecycle.LiveData
          EOL
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  download:
    if: github.event.inputs.action == 'download'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP file
        run: zip -r project.zip . -x "*.git*" "*.gradle*" "build/*" "app/build/*"
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: project-files
          path: project.zip
